version: '3.8'

services:

  mitre-analyzer:

    build:
      context: ./analyzer-engine

    container_name: mitre-analyzer

    restart: always

    network_mode: host

    volumes:

      - ./rules:/rules

      - ./attack-stix-data/enterprise-attack:/mitre
