input {

  file {

    path => "/logs/app.log"

    start_position => "beginning"

    sincedb_path => "/dev/null"
  }

}

filter {

  json {
    source => "message"
  }

  if [event] == "admin_login" and [status] == "failed" {

    mutate {

      add_field => {
        "attack_type" => "brute_force"
        "mitre_id" => "T1110"
      }

    }

  }

}

output {

  stdout {
    codec => rubydebug
  }

  elasticsearch {

    hosts => ["http://elasticsearch:9200"]

    index => "bhishi-logs"
  }

}
